### ISSUE TITLE
Native UI fallback for touch devices opens always

### ISSUE THREAD

**Issue by l0wt1de** [patrickkunka/easydropdown#36]
Hey Patrick,

First of all great work on the library!

I ran into an issue when setting nativeTouch to false on iOS 7 in Safari and Chrome. When tapping the dropdown the it opens the custom EasyDropDown options as well as the native UI.

![img_0160](https://f.cloud.github.com/assets/1293041/2032951/f3a4ee68-8915-11e3-8aff-91ca00c5e828.PNG)

I have added a quick fix for that by not focusing old inputs on touch when nativeTouch is set to false (https://github.com/codecosmetics/easydropdown/commit/f9e21c8fe463957a722b87b12852743d805e7803).

What do you think about that approach? Is there another way how you would solve this problem?

Thanks
Dirk

**Comment by patrickkunka** [comment]
Hi Dirk,

I think the issue is that the `.touch` class is still added in mobile even though native UI is disabled. This overrides the styling which hides the native UI on desktop by default.

Make sure any rules with `.touch` are removed from your css.

FYI, the disabling of native touch has not been tested very thoroughly - I'm not sure how well the dropdown will work, which is why native is usually the best option.

**Comment by darthsteven** [comment]
@codecosmetics thanks very much for your fix here. We're still using Easydropdown 2 and noticed the iOS native widget appearing along with the Easydropdown one, so were glad of your fix which seems to work, doesn't it?
