### ISSUE TITLE
Possible to have a closeOnBlur option?

### ISSUE THREAD

**Issue by brandoniffert** [patrickkunka/easydropdown#85]
When you have the `openOnFocus` option set to `true`, it allows the dropdown to open when the user is tabbing through the form and focuses the field. If the user continues to tab past the dropdown field that was opened, the dropdown stays open. It'd be nice to have a `closeOnBlur` option to automatically close the dropdown when it loses focus in this case.

I tried to setup my own listener on the `select` element, but this doesn't allow actual selection with the mouse to happen.

```js
// Works, but can't select dropdown option -
// clicking the option blurs the select before `onSelect` can fire
selectEl.addEventListener('blur', (e) => {
  easydropdown(e.target).close()
})
```

**Comment by patrickkunka** [comment]
Hi there - this seems like a very valid feature request. I'll take a look at it.

**Comment by patrickkunka** [comment]
This should be added in the latest release https://github.com/patrickkunka/easydropdown/releases/tag/4.1.0 which you can grab from npm.

Rather than add a new config option, I've built this into the existing behaviour of `openOnFocus` as it seems like it should have been there to begin with.

Let me know if it works for you.

**Comment by brandoniffert** [comment]
Works great, thank you!
